### ISSUE TITLE
Package not working with typedoc v0.24.0 because of `PageEvent` breaking change

### ISSUE THREAD

**Issue by domingo2000** [tgreyuk/typedoc-plugin-markdown#405]
With the breaking changes of TypeDoc v0.24.0 the project is not longer working

## Current Behaviour
Today I installed TypeDoc and typedoc-plugin-markdown, followed the instructions and throwed the following error.
```
TypeDoc exiting with unexpected error:
TypeError: page.template is not a function
```
I tracked the error through the files and realized that in `Theme.ts` the `Theme.render()` only takes the `page`, while in the last version of typedoc it takes `(page, template)` as specified in [Changelog](https://github.com/TypeStrong/typedoc/blob/master/CHANGELOG.md)

"PageEvent no longer includes the template property. The Theme.render method is now expected to take the template to render the page with as its second argument."

I can submit a PR to fix it

**Comment by domingo2000** [comment]
Now that I tried to make the fix, i saw that when forking the repository it installs TypeDoc 0.23, not 0.24, should i downgrade the TypeDoc in my project to make the markdown plugin works?, Or should we fix the breaking changes in the library?

**Comment by Gilbert5210** [comment]
me too

**Comment by Gilbert5210** [comment]
@tgreyuk 
can you help me???

**Comment by Gilbert5210** [comment]
@tgreyuk

**Comment by Gilbert5210** [comment]
@domingo2000 
what can you do to fix it

**Comment by tgreyuk** [comment]
Fix in typedoc-plugin-markdown@3.15.0
